### ISSUE TITLE
Error when pressing CMD +E `java.lang.NoClassDefFoundError: com/intellij/sh/SHIcons`

### ISSUE THREAD

**Issue by MuXiu1997** [Fapiko/intellij-better-direnv#16]
### Temporary Solution!

> There you go @toaster
> [better_direnv-1.0.0.zip](https://github.com/Fapiko/intellij-better-direnv/files/10461170/better_direnv-1.0.0.zip)
>
> - _Originally posted by @axaluss in https://github.com/Fapiko/intellij-better-direnv/issues/19#issuecomment-1397624676_

Thanks to @shyim and @axaluss!

***

### IntelliJ IDEA 2022.3

```log
java.lang.NoClassDefFoundError: com/intellij/sh/SHIcons
	at com.fapiko.jetbrains.plugins.better_direnv.language.filetype.DirenvFileType.getIcon(DirenvFileType.java:38)
	at com.intellij.util.IconUtil.computeFileTypeIcon(IconUtil.java:221)
	at com.intellij.util.IconUtil.computeBaseFileIcon(IconUtil.java:208)
	at com.intellij.util.IconUtil.getIcon(IconUtil.java:198)
	at com.intellij.ide.actions.SwitcherVirtualFile$icon$2.invoke(SwitcherRendering.kt:127)
	at com.intellij.ide.actions.SwitcherVirtualFile$icon$2.invoke(SwitcherRendering.kt:127)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.intellij.ide.actions.SwitcherVirtualFile.getIcon(SwitcherRendering.kt:127)
	at com.intellij.ide.actions.SwitcherVirtualFile.prepareMainRenderer(SwitcherRendering.kt:147)
	at com.intellij.ide.actions.SwitcherListRenderer.getListCellRendererComponent(SwitcherRendering.kt:194)
	at com.intellij.ide.actions.SwitcherListRenderer.getListCellRendererComponent(SwitcherRendering.kt:162)
	at com.intellij.ui.ExpandedItemListCellRendererWrapper.getListCellRendererComponent(ExpandedItemListCellRendererWrapper.java:24)
	at com.intellij.ui.components.WideSelectionListUI.updateLayoutState(WideSelectionListUI.java:197)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(BasicListUI.java:1394)
	at java.desktop/javax.swing.plaf.basic.BasicListUI$Handler.valueChanged(BasicListUI.java:2815)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:224)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:204)
	at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:251)
	at java.desktop/javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:448)
	at java.desktop/javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:458)
	at java.desktop/javax.swing.DefaultListSelectionModel.setSelectionInterval(DefaultListSelectionModel.java:502)
	at java.desktop/javax.swing.JList.setSelectedIndex(JList.java:2232)
	at com.intellij.ide.actions.Switcher$SwitcherPanel.<init>(Switcher.java:315)
	at com.intellij.ide.actions.BaseRecentFilesAction.actionPerformed(SwitcherActions.kt:65)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:323)
	at com.intellij.openapi.keymap.impl.ActionProcessor.performAction(ActionProcessor.java:47)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:584)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$9(IdeKeyEventDispatcher.java:706)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$10(IdeKeyEventDispatcher.java:706)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:346)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.doPerformActionInner(IdeKeyEventDispatcher.java:703)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:647)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:595)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:478)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:467)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:225)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:815)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:750)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:774)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:813)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.ClassNotFoundException: com.intellij.sh.SHIcons PluginClassLoader(plugin=PluginDescriptor(name=Better Direnv, id=com.fapiko.jetbrains.plugins.better_direnv, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/223.7571.182/IntelliJ IDEA.app.plugins/better_direnv, version=1.0.0, package=null, isBundled=false), packagePrefix=null, instanceId=414, state=active)
	... 54 more

```

**Comment by apane-tackle** [comment]
Same issue

**Comment by pavanmachavolu** [comment]
Same here after upgrading to latest version of Goland 2022.3

**Comment by yadavsudhir405** [comment]
Similiar issue when I use shortcut Command + shift + A to find all actions. With latest intellij version 2022.3 on mac
![Screenshot 2022-12-05 at 09 13 29](https://user-images.githubusercontent.com/11731706/205656819-eee3df74-2783-476f-9b6d-ea29ad010a68.png)

**Comment by apane-tackle** [comment]
Looks like a change to the icon import and file name.  You can't even open the project in new Intellij because of it.  DirenvFileType.java
```java
import com.intellij.sh.SHIcons;

    @Override
    public @Nullable Icon getIcon() {
        return SHIcons.ShFile;
    }
```

needs to change capitalization

```java
import com.intellij.sh.ShIcons;

    @Override
    public @Nullable Icon getIcon() {
        return ShIcons.ShFile;
    }
```

**Comment by joaosalless** [comment]
Same here after upgrading to latest version of Goland 2022.3.1

<img width="1355" alt="image" src="https://user-images.githubusercontent.com/6626712/209169031-52ad809b-0170-48bc-8e66-8f3b7e43b4fe.png">

**Comment by mdesson** [comment]
I appear to have the same issue with shift-shift (search everywhere) currently in Goland. Any updates on a fix for this issue?

**Comment by faermanj** [comment]
Same issue with shift-shift, intellij, linux

**Comment by MuXiu1997** [comment]
### Temporary Solution!

> There you go @toaster
> [better_direnv-1.0.0.zip](https://github.com/Fapiko/intellij-better-direnv/files/10461170/better_direnv-1.0.0.zip)
>
> - _Originally posted by @axaluss in https://github.com/Fapiko/intellij-better-direnv/issues/19#issuecomment-1397624676_

Thanks to @shyim and @axaluss!

**Comment by Fapiko** [comment]
Thanks for providing a fix, I've merged and deployed a new version. Usually takes a day or two to get published to the marketplace.
