### ISSUE TITLE
Bug: Double shift broken

### ISSUE THREAD

**Issue by ascheman** [Fapiko/intellij-better-direnv#21]
If I enable the plugin, the _[search everywhere](https://www.jetbrains.com/help/idea/searching-everywhere.html)_ shortcut (pressing shift shift) does not work any longer.

In the `idea.log` I find messages like this:

```
2023-01-31 07:42:18,174 [  72124] SEVERE - #c.i.i.p.PluginManager - com/intellij/sh/SHIcons
java.lang.NoClassDefFoundError: com/intellij/sh/SHIcons
        at com.fapiko.jetbrains.plugins.better_direnv.language.filetype.DirenvFileType.getIcon(DirenvFileType.java:38)
        at com.intellij.ide.util.gotoByName.FileTypeRef$Companion.forFileType(LanguageRef.kt:55)
        at com.intellij.ide.util.gotoByName.FileTypeRef$Companion.forAllFileTypes(LanguageRef.kt:61)
        at com.intellij.ide.util.gotoByName.FileTypeRef.forAllFileTypes(LanguageRef.kt)
        at com.intellij.ide.actions.searcheverywhere.FileSearchEverywhereContributor.createFileTypeFilter(FileSearchEverywhereContributor.java:167)
        at com.intellij.ide.actions.searcheverywhere.FileSearchEverywhereContributor.<init>(FileSearchEverywhereContributor.java:47)
        at com.intellij.ide.actions.searcheverywhere.RecentFilesSEContributor.<init>(RecentFilesSEContributor.java:31)
        at com.intellij.ide.actions.searcheverywhere.SearchEverywhereManagerImpl.createContributors(SearchEverywhereManagerImpl.java:175)
        at com.intellij.ide.actions.searcheverywhere.SearchEverywhereManagerImpl.show(SearchEverywhereManagerImpl.java:81)
        at com.intellij.ide.actions.SearchEverywhereBaseAction.showInSearchEverywherePopup(SearchEverywhereBaseAction.java:67)
        at com.intellij.ide.actions.GotoActionAction.actionPerformed(GotoActionAction.java:27)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:327)
        at com.intellij.openapi.keymap.impl.ActionProcessor.performAction(ActionProcessor.java:47)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:584)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$9(IdeKeyEventDispatcher.java:706)
        at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
        at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$10(IdeKeyEventDispatcher.java:706)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:350)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.doPerformActionInner(IdeKeyEventDispatcher.java:703)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:647)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:595)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:478)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:467)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:225)
        at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:815)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:750)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
        at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
        at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
        at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.ClassNotFoundException: com.intellij.sh.SHIcons PluginClassLoader(plugin=PluginDescriptor(name=Better Direnv, id=com.fapiko.jetbrains.plugins.better_direnv, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/223.8617.56/IntelliJ IDEA.app.plugins/better_direnv, version=1.0.0, package=null, isBundled=false), packagePrefix=null, instanceId=505, state=active)
        ... 41 more
2023-01-31 07:42:18,175 [  72125] SEVERE - #c.i.i.p.PluginManager - IntelliJ IDEA 2022.3.2  Build #IU-223.8617.56
2023-01-31 07:42:18,175 [  72125] SEVERE - #c.i.i.p.PluginManager - JDK: 17.0.5; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2023-01-31 07:42:18,175 [  72125] SEVERE - #c.i.i.p.PluginManager - OS: Mac OS X
2023-01-31 07:42:18,176 [  72126] SEVERE - #c.i.i.p.PluginManager - Plugin to blame: Better Direnv version: 1.0.0

```

**Comment by ascheman** [comment]
Seems like some sort of a duplicate of #16 (and #14, and #18).
Perhaps it's time to take care of the problem, @Fapiko ?

**Comment by Fapiko** [comment]
Merged and pushed a fix for this, should be available in the marketplace in a day or two once approved.
