### ISSUE TITLE
Error when running python configurations 

### ISSUE THREAD

**Issue by elonzh** [Fapiko/intellij-better-direnv#28]
```
IntelliJ IDEA 2023.1 (Ultimate Edition)
Build #IU-231.8109.175, built on March 28, 2023
Runtime version: 17.0.6+10-b829.5 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 20
Registry:
    debugger.new.tool.window.layout=true
    run.processes.with.pty=false
    editor.minimap.enabled=true

Kotlin: 231-1.8.20-IJ8109.175
```

```
com.intellij.execution.WorkingDirectoryNotFoundException: Cannot start process, the working directory '' does not exist
	at com.intellij.execution.configurations.GeneralCommandLine.validateAndPrepareCommandLine(GeneralCommandLine.java:369)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:344)
	at com.fapiko.jetbrains.plugins.better_direnv.commands.DirenvCmd.run(DirenvCmd.java:89)
	at com.fapiko.jetbrains.plugins.better_direnv.commands.DirenvCmd.importDirenv(DirenvCmd.java:52)
	at com.fapiko.jetbrains.plugins.better_direnv.settings.ui.RunConfigSettingsEditor.collectEnv(RunConfigSettingsEditor.java:73)
	at com.fapiko.jetbrains.plugins.better_direnv.runconfigs.PycharmEnvironmentProvider.extendTargetEnvironment(PycharmEnvironmentProvider.java:23)
	at com.jetbrains.python.run.PythonCommandLineState.initEnvironment(PythonCommandLineState.java:675)
	at com.jetbrains.python.run.PythonCommandLineState.buildPythonExecutionFinal(PythonCommandLineState.java:360)
	at com.jetbrains.python.run.PythonCommandLineState.startProcess(PythonCommandLineState.java:324)
	at com.jetbrains.python.run.PythonCommandLineState.execute(PythonCommandLineState.java:232)
	at com.jetbrains.python.run.PythonScriptCommandLineState.execute(PythonScriptCommandLineState.java:147)
	at com.jetbrains.python.run.PythonCommandLineState.execute(PythonCommandLineState.java:178)
	at com.jetbrains.python.run.PythonRunner.lambda$execute$2(PythonRunner.java:67)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by maddingo** [comment]
I published version [1.3.0-pre1](https://plugins.jetbrains.com/plugin/19275-better-direnv/versions/pre1?noRedirect=true) that should fix the problem. Please re-open the issue if the problem persists.
