### ISSUE TITLE
Cannot invoke "java.util.Map.size()" because "m" is null

### ISSUE THREAD

**Issue by safeuq** [Fapiko/intellij-better-direnv#36]
Occurs when running a Gradle task from IntelliJ
Error occurs in IntelliJ IDEA 2024.2 EAP
Build #IU-242.19533.56

```
java.lang.NullPointerException: Cannot invoke "java.util.Map.size()" because "m" is null
	at java.base/java.util.HashMap.putMapEntries(HashMap.java:503)
	at java.base/java.util.HashMap.putAll(HashMap.java:791)
	at com.fapiko.jetbrains.plugins.better_direnv.settings.ui.RunConfigSettingsEditor.collectEnv(RunConfigSettingsEditor.java:73)
	at com.fapiko.jetbrains.plugins.better_direnv.settings.ui.RunConfigSettingsEditor.collectEnv(RunConfigSettingsEditor.java:62)
	at com.fapiko.jetbrains.plugins.better_direnv.runconfigs.IdeaRunConfigurationExtension.updateJavaParameters(IdeaRunConfigurationExtension.java:34)
	at com.intellij.execution.RunConfigurationExtension.updateJavaParameters(RunConfigurationExtension.java:27)
	at com.intellij.execution.JavaRunConfigurationExtensionManager.updateJavaParameters(JavaRunConfigurationExtensionManager.kt:43)
	at com.intellij.execution.ExternalSystemRunConfigurationJavaExtension.updateVMParameters(ExternalSystemRunConfigurationJavaExtension.kt:62)
	at com.intellij.openapi.externalSystem.service.execution.configuration.ExternalSystemRunConfigurationExtensionManager.updateVMParameters(ExternalSystemRunConfigurationExtensionManager.kt:24)
	at com.intellij.openapi.externalSystem.service.execution.ExternalSystemRunnableState.getJvmParametersSetup(ExternalSystemRunnableState.java:422)
	at com.intellij.openapi.externalSystem.service.execution.ExternalSystemRunnableState.execute(ExternalSystemRunnableState.java:189)
	at com.intellij.openapi.externalSystem.service.execution.ExternalSystemTaskRunner.doExecute(ExternalSystemTaskRunner.kt:37)
	at com.intellij.openapi.externalSystem.service.execution.ExternalSystemTaskRunner.access$doExecute(ExternalSystemTaskRunner.kt:18)
	at com.intellij.openapi.externalSystem.service.execution.ExternalSystemTaskRunner$execute$1.invoke(ExternalSystemTaskRunner.kt:28)
	at com.intellij.openapi.externalSystem.service.execution.ExternalSystemTaskRunner$execute$1.invoke(ExternalSystemTaskRunner.kt:27)
	at com.intellij.execution.impl.ExecutionManagerImpl$startRunProfile$1.invoke(ExecutionManagerImpl.kt:223)
	at com.intellij.execution.impl.ExecutionManagerImpl$startRunProfile$1.invoke(ExecutionManagerImpl.kt:221)
	at com.intellij.execution.impl.ExecutionManagerImpl.doStartRunProfile$lambda$2(ExecutionManagerImpl.kt:286)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:229)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runIntendedWriteActionOnCurrentThread$lambda$1(AnyThreadWriteThreadingSupport.kt:184)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:84)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runIntendedWriteActionOnCurrentThread(AnyThreadWriteThreadingSupport.kt:183)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:836)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:425)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWithImplicitRead(AnyThreadWriteThreadingSupport.kt:122)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithImplicitRead(ApplicationImpl.java:1162)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:78)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:119)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:750)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:696)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$16(IdeEventQueue.kt:590)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWithoutImplicitRead(AnyThreadWriteThreadingSupport.kt:117)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:590)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:73)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1$1.compute(IdeEventQueue.kt:357)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1$1.compute(IdeEventQueue.kt:356)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:843)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.invoke(IdeEventQueue.kt:356)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.invoke(IdeEventQueue.kt:351)
	at com.intellij.ide.IdeEventQueueKt$performActivity$runnableWithWIL$1.invoke$lambda$0(IdeEventQueue.kt:1035)
	at com.intellij.openapi.application.WriteIntentReadAction.lambda$run$0(WriteIntentReadAction.java:24)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:84)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteIntentReadAction(ApplicationImpl.java:910)
	at com.intellij.openapi.application.WriteIntentReadAction.compute(WriteIntentReadAction.java:55)
	at com.intellij.openapi.application.WriteIntentReadAction.run(WriteIntentReadAction.java:23)
	at com.intellij.ide.IdeEventQueueKt$performActivity$runnableWithWIL$1.invoke(IdeEventQueue.kt:1035)
	at com.intellij.ide.IdeEventQueueKt$performActivity$runnableWithWIL$1.invoke(IdeEventQueue.kt:1035)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1036)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1036)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$10(IdeEventQueue.kt:351)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:397)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by Goofy-lee** [comment]
does anyone have a solution??

**Comment by levzem** [comment]
I have something similar when trying to run a test in PyCharm

```
Worker exited due to exception

java.lang.NullPointerException: Cannot invoke "java.util.Map.size()" because "m" is null
	at java.base/java.util.HashMap.putMapEntries(HashMap.java:503)
	at java.base/java.util.HashMap.putAll(HashMap.java:791)
	at com.fapiko.jetbrains.plugins.better_direnv.settings.ui.RunConfigSettingsEditor.collectEnv(RunConfigSettingsEditor.java:73)
	at com.fapiko.jetbrains.plugins.better_direnv.runconfigs.PycharmEnvironmentProvider.extendTargetEnvironment(PycharmEnvironmentProvider.java:26)
	at com.jetbrains.python.run.PythonCommandLineState.initEnvironment(PythonCommandLineState.java:680)
	at com.jetbrains.python.run.PythonCommandLineState.buildPythonExecutionFinal(PythonCommandLineState.java:360)
	at com.jetbrains.python.run.PythonCommandLineState.startProcess(PythonCommandLineState.java:323)
	at com.jetbrains.python.testing.PythonTestCommandLineStateBase.execute(PythonTestCommandLineStateBase.java:164)
	at com.jetbrains.python.run.PythonCommandLineState.execute(PythonCommandLineState.java:181)
	at com.jetbrains.python.run.PythonRunner.lambda$execute$2(PythonRunner.java:68)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by james-johnston-thumbtack** [comment]
I get this similar stack trace when trying to run a test in Go:

This is with:
- Better Direnv 1.2.2
- Go plugin 243.22562.145
- IntelliJ IDEA 2024.3.1 (Ultimate Edition)
  - Build #IU-243.22562.145, built on December 8, 2024

```
java.lang.NullPointerException: Cannot invoke "java.util.Map.size()" because "m" is null
	at java.base/java.util.HashMap.putMapEntries(HashMap.java:503)
	at java.base/java.util.HashMap.putAll(HashMap.java:791)
	at com.fapiko.jetbrains.plugins.better_direnv.settings.ui.RunConfigSettingsEditor.collectEnv(RunConfigSettingsEditor.java:73)
	at com.fapiko.jetbrains.plugins.better_direnv.runconfigs.GolandRunConfigurationExtension.patchCommandLine(GolandRunConfigurationExtension.java:56)
	at com.goide.execution.extension.GoRunConfigurationExtensionsManager.lambda$patchCommandLine$2(GoRunConfigurationExtensionsManager.java:74)
	at com.intellij.execution.configuration.RunConfigurationExtensionsManager.processEnabledExtensions(RunConfigurationExtensionsManager.kt:224)
	at com.goide.execution.extension.GoRunConfigurationExtensionsManager.patchCommandLine(GoRunConfigurationExtensionsManager.java:72)
	at com.goide.execution.GoRunningState.lambda$patchCommandLine$7(GoRunningState.java:341)
	at com.goide.util.GoExecutor.createCommandLine(GoExecutor.java:1015)
	at com.goide.util.GoExecutor$3.getProcessHandler(GoExecutor.java:614)
	at com.goide.util.GoExecutor$3.run(GoExecutor.java:569)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:491)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:133)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$7(CoreProgressManager.java:542)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:249)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:98)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:223)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:45)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:222)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$14(CoreProgressManager.java:674)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:749)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:673)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:203)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:98)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:249)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:502)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:467)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:107)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:101)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$19(ProgressRunner.java:463)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by JiangHongTiao** [comment]
I also keep getting this error and not able to run those configurations.

**Comment by lenalebt** [comment]
same here

**Comment by fatso83** [comment]
This happens if .envrc is not present as well. There should be a check for this.

**Comment by maddingo** [comment]
I published version [1.3.0-pre1](https://plugins.jetbrains.com/plugin/19275-better-direnv/versions/pre1?noRedirect=true) that should fix the problem. Please re-open the issue if the problem persists.

**Comment by fatso83** [comment]
@maddingo any idea how I can get that pre-release to show up in IntelliJ? I cannot figure out how to enable the pre-stable channel

**Comment by maddingo** [comment]
Sorry for the late reply, I release 1.4.0, which should appear in the
normal release channel.

--
Martin

**Comment by fatso83** [comment]
I was able to trigger download the pre-release via the UI, so I just wanted to say it works fine :-)
